server:
    port: 8080
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/kotlinblog?serverTimezone=Asia/Seoul
        username: root
        password: 1234
    jpa:
        hibernate:
            ddl-auto: update
            shw_sql: true
        database:
            platform: org.hibernate.dialect.MySQL8Dialect
    devtools:
        restart:
            enabled: true